# Generated by Django 3.2.5 on 2021-07-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='cvr_url',
            new_name='cover_url',
        ),
    ]
